### ISSUE TITLE
Program does not work with files in other directories

### ISSUE THREAD

**Issue by mvences** [akshatgui/sequence-editor#6]
This is only a minor bug, probably related to how Windows vs. Linus is indexing files and directories. When trying to open a file that is in a different directory than the program, I get this error message:
![Capture2](https://user-images.githubusercontent.com/66744055/149189689-6df5382f-3478-442d-b6f7-337dc8762e90.PNG)

**Comment by tanmaysachan** [comment]
The whitespace in the folder name "Stuff 2021" was causing the issue. It should be fixed now.
